name: Build on CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
    name: Deploy
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install esy
        run: npm install -g esy@dev
      - uses: esy/github-action@prometheansacrifice/fix-prefix-not-passed-to-esy-commands
        with:
          source-cache-key: 20240626-1
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-20240626-1

